In [ ]:
import pyreadr

# Load the rds file
result = pyreadr.read_r('06_Cb_BTM_table.rds')

# pyreadr returns a dictionary; the data is usually under the 'None' key 
# because rds files contain a single object without a specific name.
df = result[None]

df = df[df['mutatation_status']!="WT"]

# select ttype 

ttype = "OV"

df = df[df["ttype"]==ttype]

df = df.dropna(subset=["clock_rank","gene"])

df

,segment_id,gene,karyotype,sample_id,NV,DP,mutatation_status,mult_estimate,mutation_call,timed,...,clock_mean,clock_low,clock_high,clock_rank,class,is_WGD,ploidy,purity,best_K,ttype
2853,chr11:106171203:109248834:2:2:1,ATM,2:2,09508a0d-ebe0-4fa1-b7b2-1710814181cd,26.0,53.0,CI_M,2.0,NaN,True,...,0.840360,0.764048,0.895425,1,WGD,wgd,4.0,0.704,1.0,OV
2855,chr8:115880031:121037910:2:2:1,RAD21,2:2,09508a0d-ebe0-4fa1-b7b2-1710814181cd,22.0,77.0,CI_M,1.0,NaN,True,...,0.840360,0.764048,0.895425,1,WGD,wgd,4.0,0.704,1.0,OV
2856,chr8:115880031:121037910:2:2:1,RAD21,2:2,09508a0d-ebe0-4fa1-b7b2-1710814181cd,14.0,35.0,CI_M,2.0,NaN,True,...,0.840360,0.764048,0.895425,1,WGD,wgd,4.0,0.704,1.0,OV
11527,chr5:59760230:76055561:2:2:1,KIF2A,2:2,0ead45d8-d785-4404-8319-2ef951e02e03,16.0,61.0,CI_M,2.0,NaN,True,...,0.797943,0.709609,0.862686,1,WGD,wgd,2.0,0.456,1.0,OV
12342,chr17:27449264:39964257:2:0:1,NF1,2:0,123c9d1c-72ba-4d82-8e57-d5caa52a40ba,NaN,NaN,CNA_driver,NaN,NaN,True,...,0.759961,0.658954,0.836128,1,WGD,wgd,2.0,0.770,1.0,OV
17888,chr3:172298406:180016684:2:1:1,PIK3CA,2:1,2b40a733-7a63-4bb8-a953-95a4ee28f962,17.0,80.0,M,1.0,in PCAWG driver annotation,True,...,0.126447,0.056244,0.255583,1,Classic,no_wgd,2.0,0.671,5.0,OV
23501,chr17:12500:46599068:2:0:1,NF1,2:0,42465bbd-289b-4e96-98fe-76809c5e1520,29.0,58.0,M,2.0,in PCAWG driver annotation,True,...,0.930777,0.905945,0.948441,1,WGD,wgd,2.0,0.501,1.0,OV
23502,chr17:12500:46599068:2:0:1,BRCA1,2:0,42465bbd-289b-4e96-98fe-76809c5e1520,22.0,45.0,M,2.0,in PCAWG driver annotation,True,...,0.930777,0.905945,0.948441,1,WGD,wgd,2.0,0.501,1.0,OV
25036,chr12:48125163:52840956:2:1:1,KMT2D,2:1,4679f37a-4f09-449b-a1d8-1f02847996da,18.0,57.0,M,1.0,in PCAWG driver annotation,True,...,0.310159,0.226180,0.402337,1,HM,no_wgd,2.0,0.940,2.0,OV
25037,chr17:43905458:81195209:2:0:1,TP53,2:0,4679f37a-4f09-449b-a1d8-1f02847996da,NaN,NaN,M,NaN,in PCAWG driver annotation but missing,True,...,0.857951,0.805853,0.900144,2,HM,no_wgd,2.0,0.940,2.0,OV
25038,chr2:108251143:129685918:2:0:1,BUB1,2:0,4679f37a-4f09-449b-a1d8-1f02847996da,23.0,46.0,CI_M,1.0,NaN,True,...,0.857951,0.805853,0.900144,2,HM,no_wgd,2.0,0.940,2.0,OV
27142,chr3:118593966:153759098:2:2:1,STAG1,2:2,4e913899-eeb8-4630-ba9d-41a81ced8069,4.0,52.0,CI_M,1.0,NaN,True,...,0.786497,0.691588,0.856846,1,WGD,wgd,2.0,0.470,1.0,OV
28093,chr22:12200000:51304565:2:0:1,NF2,2:0,504cdfc5-6721-43ef-b31e-fdf52f0cd9cd,38.0,56.0,M,2.0,in PCAWG driver annotation,True,...,0.618181,0.535961,0.687872,1,WGD,wgd,2.0,0.600,1.0,OV
28094,chr13:16300000:63587432:2:0:1,RB1,2:0,504cdfc5-6721-43ef-b31e-fdf52f0cd9cd,NaN,NaN,CNA_driver,NaN,NaN,True,...,0.618181,0.535961,0.687872,1,WGD,wgd,2.0,0.600,1.0,OV
35841,chr18:27500:52703431:2:1:1,SMAD4,2:1,6821446e-8e76-46fe-b0b9-47feb46d2585,32.0,56.0,M,2.0,in PCAWG driver annotation,True,...,0.297768,0.224827,0.375448,2,WGD,wgd,3.0,0.679,2.0,OV
35842,chr3:122097802:163393856:2:1:1,STAG1,2:1,6821446e-8e76-46fe-b0b9-47feb46d2585,11.0,70.0,CI_M,1.0,NaN,True,...,0.297768,0.224827,0.375448,2,WGD,wgd,3.0,0.679,2.0,OV
45296,chr1:6040064:36447539:2:0:1,ARID1A,2:0,8b28f6d2-4b7d-493b-826e-b119a4fb0cb4,NaN,NaN,CNA_driver,NaN,NaN,True,...,0.123594,0.082953,0.183001,1,WGD,wgd,2.0,0.661,2.0,OV
45297,chr13:44864707:66618180:2:0:1,RB1,2:0,8b28f6d2-4b7d-493b-826e-b119a4fb0cb4,NaN,NaN,CNA_driver,NaN,NaN,True,...,0.123594,0.082953,0.183001,1,WGD,wgd,2.0,0.661,2.0,OV
45298,chr10:124430588:135262499:2:0:1,BUB3,2:0,8b28f6d2-4b7d-493b-826e-b119a4fb0cb4,29.0,52.0,CI_M,2.0,NaN,True,...,0.560936,0.476573,0.633425,2,WGD,wgd,2.0,0.661,2.0,OV
45299,chr3:131628405:137813497:2:1:1,STAG1,2:1,8b28f6d2-4b7d-493b-826e-b119a4fb0cb4,13.0,64.0,CI_M,1.0,NaN,True,...,0.123594,0.082953,0.183001,1,WGD,wgd,2.0,0.661,2.0,OV
45300,chr3:131628405:137813497:2:1:1,STAG1,2:1,8b28f6d2-4b7d-493b-826e-b119a4fb0cb4,14.0,52.0,CI_M,1.0,NaN,True,...,0.123594,0.082953,0.183001,1,WGD,wgd,2.0,0.661,2.0,OV
45301,chr3:131628405:137813497:2:1:1,STAG1,2:1,8b28f6d2-4b7d-493b-826e-b119a4fb0cb4,15.0,64.0,CI_M,1.0,NaN,True,...,0.123594,0.082953,0.183001,1,WGD,wgd,2.0,0.661,2.0,OV
45302,chr3:131628405:137813497:2:1:1,STAG1,2:1,8b28f6d2-4b7d-493b-826e-b119a4fb0cb4,12.0,52.0,CI_M,1.0,NaN,True,...,0.123594,0.082953,0.183001,1,WGD,wgd,2.0,0.661,2.0,OV
50907,chr13:1:49164399:2:0:1,RB1,2:0,9e6806c4-d331-4025-abee-2f576e3bf182,31.0,36.0,M,2.0,in PCAWG driver annotation,True,...,0.845643,0.769311,0.898686,1,WGD,wgd,4.0,0.810,1.0,OV
50908,chr16:44080:5124427:2:0:1,CREBBP,2:0,9e6806c4-d331-4025-abee-2f576e3bf182,NaN,NaN,CNA_driver,NaN,NaN,True,...,0.845643,0.769311,0.898686,1,WGD,wgd,4.0,0.810,1.0,OV
50909,chr5:53957804:99266416:2:0:1,KIF2A,2:0,9e6806c4-d331-4025-abee-2f576e3bf182,20.0,24.0,CI_M,2.0,NaN,True,...,0.845643,0.769311,0.898686,1,WGD,wgd,4.0,0.810,1.0,OV
50910,chr5:53957804:99266416:2:0:1,KIF2A,2:0,9e6806c4-d331-4025-abee-2f576e3bf182,14.0,30.0,CI_M,1.0,NaN,True,...,0.845643,0.769311,0.898686,1,WGD,wgd,4.0,0.810,1.0,OV
52175,chr3:117152140:137791339:2:2:1,STAG1,2:2,a3135834-3af0-4e98-bc6f-ad8ddf33db80,12.0,68.0,CI_M,1.0,NaN,True,...,0.194760,0.129179,0.270656,1,WGD,wgd,3.0,0.664,2.0,OV
58625,chr17:46579060:81195209:2:0:1,TP53,2:0,b97941dd-9844-4db2-9e25-42c725f47d70,NaN,NaN,M,NaN,in PCAWG driver annotation but missing,True,...,0.547059,0.387103,0.707251,1,Classic,no_wgd,2.0,0.612,1.0,OV
59751,chr17:25800000:43285732:2:1:1,CDK12,2:1,bbe59385-5f83-43f6-a485-517c860bef6f,11.0,34.0,M,1.0,in PCAWG driver annotation,True,...,0.596390,0.507589,0.674784,1,WGD,wgd,4.0,0.782,1.0,OV
59752,chr17:25800000:43285732:2:1:1,CDK12,2:1,bbe59385-5f83-43f6-a485-517c860bef6f,11.0,30.0,M,1.0,in PCAWG driver annotation,True,...,0.596390,0.507589,0.674784,1,WGD,wgd,4.0,0.782,1.0,OV
59753,chr16:46415803:90354752:2:0:1,CBFB,2:0,bbe59385-5f83-43f6-a485-517c860bef6f,NaN,NaN,M,NaN,in PCAWG driver annotation but missing,True,...,0.596390,0.507589,0.674784,1,WGD,wgd,4.0,0.782,1.0,OV
60316,chr17:33904481:43177765:2:0:1,BRCA1,2:0,bc9b66f5-fcb8-4545-ab2d-438bb810edc0,NaN,NaN,CNA_driver,NaN,NaN,True,...,0.719550,0.632713,0.794922,2,HM,no_wgd,2.0,0.642,2.0,OV
61735,chr17:1665:28062757:2:0:1,TP53,2:0,c767254e-b289-4904-a80f-050cf01ff8ba,19.0,26.0,M,2.0,in PCAWG driver annotation,True,...,0.158662,0.103052,0.248370,2,WGD,wgd,2.0,0.724,4.0,OV
61736,chr1:26381098:33203299:2:0:1,ARID1A,2:0,c767254e-b289-4904-a80f-050cf01ff8ba,NaN,NaN,CNA_driver,NaN,NaN,True,...,0.158662,0.103052,0.248370,2,WGD,wgd,2.0,0.724,4.0,OV
61737,chr10:103405426:134111124:2:1:1,SMC3,2:1,c767254e-b289-4904-a80f-050cf01ff8ba,25.0,37.0,CI_M,2.0,NaN,True,...,0.874348,0.805660,0.917682,4,WGD,wgd,2.0,0.724,4.0,OV
64676,chr3:132516523:147988265:2:1:1,ATR,2:1,cf6c7066-6611-43ec-aef1-295a976cce5b,16.0,69.0,CI_M,1.0,NaN,True,...,0.072540,0.046939,0.116057,1,WGD,wgd,3.0,0.882,2.0,OV
64677,chr3:132516523:147988265:2:1:1,STAG1,2:1,cf6c7066-6611-43ec-aef1-295a976cce5b,14.0,47.0,CI_M,1.0,NaN,True,...,0.072540,0.046939,0.116057,1,WGD,wgd,3.0,0.882,2.0,OV
65386,chr6:72348757:170899800:2:0:1,LATS1,2:0,d2e4dc23-992d-4e44-add4-2972718083cb,23.0,25.0,M,2.0,in PCAWG driver annotation,True,...,0.881390,0.811546,0.925606,1,WGD,wgd,2.0,0.858,1.0,OV
65387,chr2:101433432:120401902:2:2:1,BUB1,2:2,d2e4dc23-992d-4e44-add4-2972718083cb,18.0,44.0,CI_M,2.0,NaN,True,...,0.881390,0.811546,0.925606,1,WGD,wgd,2.0,0.858,1.0,OV
65388,chr5:51692889:73819399:2:0:1,KIF2A,2:0,d2e4dc23-992d-4e44-add4-2972718083cb,30.0,36.0,CI_M,2.0,NaN,True,...,0.881390,0.811546,0.925606,1,WGD,wgd,2.0,0.858,1.0,OV
65759,chr10:100556679:116606532:2:2:1,SMC3,2:2,d4bf6034-aeae-48a6-907b-10e2cc904015,8.0,41.0,CI_M,1.0,NaN,True,...,0.037235,0.020910,0.066024,1,WGD,wgd,3.0,0.684,2.0,OV
66520,chr13:55117671:99688413:2:0:1,DIS3,2:0,d8c2b4b2-e12b-43d2-bafc-87b29f027797,7.0,47.0,M,1.0,in PCAWG driver annotation,True,...,0.739010,0.649602,0.815738,3,WGD,wgd,2.0,0.844,3.0,OV
66521,chr11:102512073:118442120:2:1:1,ATM,2:1,d8c2b4b2-e12b-43d2-bafc-87b29f027797,11.0,52.0,CI_M,1.0,NaN,True,...,0.242474,0.165028,0.340690,2,WGD,wgd,2.0,0.844,3.0,OV
66522,chr11:102512073:118442120:2:1:1,ATM,2:1,d8c2b4b2-e12b-43d2-bafc-87b29f027797,20.0,74.0,CI_M,1.0,NaN,True,...,0.242474,0.165028,0.340690,2,WGD,wgd,2.0,0.844,3.0,OV
66523,chr3:107732541:149339233:2:1:1,STAG1,2:1,d8c2b4b2-e12b-43d2-bafc-87b29f027797,20.0,54.0,CI_M,1.0,NaN,True,...,0.050607,0.029206,0.088032,1,WGD,wgd,2.0,0.844,3.0,OV
66524,chr3:107732541:149339233:2:1:1,STAG1,2:1,d8c2b4b2-e12b-43d2-bafc-87b29f027797,13.0,54.0,CI_M,1.0,NaN,True,...,0.050607,0.029206,0.088032,1,WGD,wgd,2.0,0.844,3.0,OV
67368,chr1:24395341:28425859:2:0:1,ARID1A,2:0,da43386c-47f8-4e03-b6ca-8b94e13792e7,NaN,NaN,CNA_driver,NaN,NaN,True,...,0.207990,0.147988,0.278450,1,WGD,wgd,3.0,0.488,2.0,OV
67369,chr17:2500:46099521:2:0:1,BRCA1,2:0,da43386c-47f8-4e03-b6ca-8b94e13792e7,NaN,NaN,CNA_driver,NaN,NaN,True,...,0.207990,0.147988,0.278450,1,WGD,wgd,3.0,0.488,2.0,OV
68577,chr3:133185467:149257235:2:1:1,STAG1,2:1,dce54d09-9827-4fe2-abe1-c5b7d528ba7f,45.0,80.0,CI_M,2.0,NaN,True,...,0.780834,0.694973,0.845738,2,HM,no_wgd,2.0,0.949,2.0,OV
70036,chr5:56188335:67871588:2:1:1,KIF2A,2:1,e4aaca83-3ae9-47f6-a975-c144767ad705,9.0,41.0,CI_M,1.0,NaN,True,...,0.098111,0.059049,0.157572,1,WGD,wgd,3.0,0.498,1.0,OV
70785,chr6:147582760:170899800:2:0:1,ARID1B,2:0,e84debc4-b47d-48ed-a0d0-2859f0ebf987,NaN,NaN,M,NaN,in PCAWG driver annotation but missing,True,...,0.746710,0.655439,0.821379,2,Classic,no_wgd,2.0,0.500,2.0,OV
73386,chr11:107200252:112818878:2:1:1,ATM,2:1,efbec43c-0c16-4006-abe8-c3ec2ec42c05,12.0,55.0,CI_M,1.0,NaN,True,...,0.667378,0.594918,0.736391,1,Classic,no_wgd,2.0,0.580,1.0,OV
73505,chr17:12500:21294732:2:0:1,TP53,2:0,efec3225-de07-4559-9a90-95223495cc61,35.0,46.0,M,2.0,in PCAWG driver annotation,True,...,0.667623,0.572171,0.751501,2,Classic,no_wgd,1.0,0.789,2.0,OV

In [ ]:
df.

In [ ]:
trees = {}

patients = df["sample_id"].unique()

interesting_p = 0
max_gene = 0


for p in patients:
    df_p = df[df["sample_id"] == p]
    genes_found = df_p.shape[0]
    ranks = int(df_p["clock_rank"].unique().max())
    if genes_found >= max_gene:
        print("Found interesting patient idx ",interesting_p, " with genes : ", genes_found)
        max_gene = genes_found
        df_int = df_p
    genes = {}
    for r in range(1,ranks+1):
        df_p_r =  df_p[df_p["clock_rank"]==r]
        #take Gene and Status 
        couple = df_p_r[['gene', 'mutatation_status']].drop_duplicates()
        #couple = df_p_r[['gene', 'mutatation_status']]
        genes_list = [f"{row[0]} ({row[1]})" for row in couple.values]        
        if len(genes_list)>0: #some ranks are skipped ????
            genes[r] = genes_list
    trees[p] = genes
    interesting_p += 1
    
'''for k,v in trees.items():
    for k2,v2 in v.items():   
        print(k,k2,v2)'''

Found interesting patient idx  0  with genes :  3
Found interesting patient idx  5  with genes :  3
Found interesting patient idx  9  with genes :  7

'for k,v in trees.items():\n    for k2,v2 in v.items():   \n        print(k,k2,v2)'

In [12]:
from utils import plot_tree as pt


p = patients[9]

print(trees[p])

pt.print_tree(trees[p],"rank_same.gv")

{1: ['ARID1A (CNA_driver)', 'RB1 (CNA_driver)', 'STAG1 (CI_M)', 'STAG1 (CI_M)', 'STAG1 (CI_M)', 'STAG1 (CI_M)'], 2: ['BUB3 (CI_M)']}

## Perchè lo stesso gene viene ripetuto? 
Il gene è composto da tantissime basi (lettere); in questo dataset abbiamo l'elenco delle mutazioni (errori delle lettere), non dei geni. 

Quindi, se lo stesso gene compare più volte, vuol dire che in esso sono presenti più mutazioni puntiformi. Il gene si trova in uno specifico cromosoma e uno specifico segmento, l'unica cosa che cambia sono i dati di sequenziamento. 

DP/NV: riguardano come la sequenza del gene viene letta dal sequenziatore. 
* DP: profondità, numero di volte in cui il sequenziatore ha letto quel segmento del dna; 
* NV: numero di variants, numero di volte in cui leggendo quel punto, il sequenziatore ha trovato un variante (lettera sbagliata)

Quindi il tumore ha accumulato 5 mutazioni puntiformi diverse (M) in 5 punti diversi del gene STAG1. All'istante di clock_mean, il cromosoma che lo conteneva si è amplificato: loro non hanno trovato quando sono avvenute queste mutazioni, MA solo quando è avvenuta la duplicazione del segmento cromosomico(ovviamente tutte le 5 mutazioni avranno lo stesso clock_mean).

In [2]:
import pyreadr

# Load the rds file
result = pyreadr.read_r('06_Cb_BTM_table.rds')

# pyreadr returns a dictionary; the data is usually under the 'None' key 
# because rds files contain a single object without a specific name.
df = result[None]

# Show all columns

print("-"*50+"Columns name"+50*"-")
print(df.columns)
print("-"*50+"Columns name"+50*"-")
df

--------------------------------------------------Columns name--------------------------------------------------
Index(['segment_id', 'gene', 'karyotype', 'sample_id', 'NV', 'DP',
       'mutatation_status', 'mult_estimate', 'mutation_call', 'timed',
       'segment_name', 'sample', 'n_mutations', 'clock_mean', 'clock_low',
       'clock_high', 'clock_rank', 'class', 'is_WGD', 'ploidy', 'purity',
       'best_K', 'ttype'],
      dtype='str')
--------------------------------------------------Columns name--------------------------------------------------

,segment_id,gene,karyotype,sample_id,NV,DP,mutatation_status,mult_estimate,mutation_call,timed,...,clock_mean,clock_low,clock_high,clock_rank,class,is_WGD,ploidy,purity,best_K,ttype
0,chr1:33554784:48120521:2:2:1,CDC20,2:2,0009b464-b376-4fbc-8a56-da538269a02f,NaN,NaN,WT,NaN,NaN,True,...,0.214457,0.141665,0.312623,1,WGD,wgd,3.0,0.885,1.0,OV
1,chr1:33554784:48120521:2:2:1,CSF3R,2:2,0009b464-b376-4fbc-8a56-da538269a02f,NaN,NaN,WT,NaN,NaN,True,...,0.214457,0.141665,0.312623,1,WGD,wgd,3.0,0.885,1.0,OV
2,chr1:33554784:48120521:2:2:1,MPL,2:2,0009b464-b376-4fbc-8a56-da538269a02f,NaN,NaN,WT,NaN,NaN,True,...,0.214457,0.141665,0.312623,1,WGD,wgd,3.0,0.885,1.0,OV
3,chr1:33554784:48120521:2:2:1,RRAGC,2:2,0009b464-b376-4fbc-8a56-da538269a02f,NaN,NaN,WT,NaN,NaN,True,...,0.214457,0.141665,0.312623,1,WGD,wgd,3.0,0.885,1.0,OV
4,chr1:33554784:48120521:2:2:1,TAL1,2:2,0009b464-b376-4fbc-8a56-da538269a02f,NaN,NaN,WT,NaN,NaN,True,...,0.214457,0.141665,0.312623,1,WGD,wgd,3.0,0.885,1.0,OV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89691,chr5:137765178:180687907:2:0:1,FLT4,2:0,ffe4bb51-e98a-41a7-a4e1-c3970386889c,NaN,NaN,WT,NaN,NaN,True,...,0.861555,0.760277,0.923399,1,Classic,no_wgd,2.0,0.853,1.0,PACA
89692,chr5:137765178:180687907:2:0:1,NPM1,2:0,ffe4bb51-e98a-41a7-a4e1-c3970386889c,NaN,NaN,WT,NaN,NaN,True,...,0.861555,0.760277,0.923399,1,Classic,no_wgd,2.0,0.853,1.0,PACA
89693,chr5:137765178:180687907:2:0:1,NSD1,2:0,ffe4bb51-e98a-41a7-a4e1-c3970386889c,NaN,NaN,WT,NaN,NaN,True,...,0.861555,0.760277,0.923399,1,Classic,no_wgd,2.0,0.853,1.0,PACA
89694,chr5:137765178:180687907:2:0:1,PDGFRB,2:0,ffe4bb51-e98a-41a7-a4e1-c3970386889c,NaN,NaN,WT,NaN,NaN,True,...,0.861555,0.760277,0.923399,1,Classic,no_wgd,2.0,0.853,1.0,PACA
89695,chr5:137765178:180687907:2:0:1,PWWP2A,2:0,ffe4bb51-e98a-41a7-a4e1-c3970386889c,NaN,NaN,WT,NaN,NaN,True,...,0.861555,0.760277,0.923399,1,Classic,no_wgd,2.0,0.853,1.0,PACA